


################################################################################
# request-info - https://github.com/behaviorbot/request-info                   #
################################################################################

requestInfoReplyComment: >
  Hi! Thanks for taking the time to create an issue!
  We would appreciate it if you could provide us with more info about this issue/pr!

# default titles to check against for lack of descriptiveness
requestInfoDefaultTitles:
  - update readme.md
  - updates
  - not working

requestInfoLabelToAdd: "Waiting for info"


################################################################################
# new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome         #
################################################################################

newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
  Read [this article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) on how to report bugs if you need some guidelines :)


################################################################################
# new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
################################################################################

newPRWelcomeComment: >
  Thanks for opening this pull request!


################################################################################
# first-pr-merge - https://github.com/behaviorbot/first-pr-merge               #
################################################################################

firstPRMergeComment: >
  Congrats on merging your first pull request! Your effort is highly appreciated!


