dist: bionic
git:
  submodules: false

env:
  global:
  - 'CACHEDIR=/home/travis/.cache/miicam/src'
  - 'WEBHOOK=https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh'

cache:
  directories:
    - /home/travis/.cache/miicam/src

jobs:
  include:
  ##############################################################################
  ## Build web ui                                                             ##
  ##############################################################################

  - name: Webui
    sudo: required

    language: php
    php:
      - '7.3.17'

    before_install:
    - composer global require hirak/prestissimo mediamonks/composer-vendor-cleaner

    script:
    - cd ${TRAVIS_BUILD_DIR}/web
    - composer install --no-dev --ignore-platform-reqs --no-interaction --prefer-source
    - php /home/travis/.config/composer/vendor/mediamonks/composer-vendor-cleaner/bin/clean --dir ${TRAVIS_BUILD_DIR}/web/vendor/
    - composer dump-autoload --classmap-authoritative
    - find ${TRAVIS_BUILD_DIR}/web/vendor -type l -delete
    - printf '{"tag":"%s","commit":"%s","commit_message":"%s","build_log":"%s"}' "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$TRAVIS_COMMIT_MESSAGE" "$TRAVIS_BUILD_WEB_URL" > ${TRAVIS_BUILD_DIR}/web/public/static/version.json
    - tar -czf website.tgz -C ${TRAVIS_BUILD_DIR}/web app libs public vendor
    - md5sum website.tgz > website.md5sum

    before_deploy:
    - git config --local user.name "Travis Releases Build Bot"
    - git config --local user.email "miicam@fliphess.com"
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

    deploy:
      provider: releases
      api_key:
        secure: tQzN8M2tmdruwXiISw3rXMoz9ZNNOIabOC9MCxjihbQiQ5rXC3dqRlqtq3YC5PIg+FkfPuTH7OLH9QrC1N2O6sPD8VKsDkFMHyY3NG6AXfvpBVAP+u0RfH2hOxVQyMQ5DnvSFlGcYkef3X7OypRHcFSJSx5+IZHkPFkOpSxVQJu3PCGicO4qFRa2ALev/hosLO8zH8TN0cJi8353EXqH6f6mHoJTsLI0WpcZ0Bql4g1QqlEb6cs34rJB53ydboClv8E1fIG1E15k83kTa5J7hoGUVHfzWP0sode1vZbdr7gpMtAzL+kpuHTOZ+YsS63HxC+M7lw4UPKBDZ1v0nPPX1rW177kGOMBzCHlqXhgK3fhMpZ9BZ58gFklFa4tqrbJSLq2jNYm4EWK7JM5TycMhkl4EwqEe4UdxXgj28WeehsBUChGqAS6ofpvHCf/mVg3cF7Px/MVhChA4JVPl8UV0sY5jlQwGXuEaNh10+yq0faSH9kWwkdCX3aeq2CXi5h5eB+Lac4Wt0YlnEmqZAVv1N01TqD29naXEuzJ2P5xw9rc1nWV1wiRmu1TQ+kwmoEbjGscIMxFO1tUfa1lPm30Ik1yKmitA5oIZTYGyXW9lPegsMOHxpkuTAZzw6KhCKUrdrP2XdPFT7fjelZe5fB/U4aEb8Y+S5OPYyaQQq1wVkI=
      file_glob: true
      file: website.*
      skip_cleanup: true
      on:
        tags: true

  ##############################################################################
  ## Build stage                                                              ##
  ##############################################################################
  - name: Build
    sudo: required
    language: python
    python: 3.6

    before_install:
    - docker ps -a
    - docker pull quay.io/miicam/miicam
    - docker build --cache-from quay.io/miicam/miicam -t miicam/miicam .
    script:
    - mkdir -p "${CACHEDIR}"
    - docker run -i -v "$(pwd):/result" -v "${CACHEDIR}:/env/src" --detach=false --rm --tty=true miicam/miicam /bin/bash -c 'make images clean && cp /env/MiiCam.* /result/'

    services:
    - docker

    deploy:
      provider: releases
      api_key:
        secure: tQzN8M2tmdruwXiISw3rXMoz9ZNNOIabOC9MCxjihbQiQ5rXC3dqRlqtq3YC5PIg+FkfPuTH7OLH9QrC1N2O6sPD8VKsDkFMHyY3NG6AXfvpBVAP+u0RfH2hOxVQyMQ5DnvSFlGcYkef3X7OypRHcFSJSx5+IZHkPFkOpSxVQJu3PCGicO4qFRa2ALev/hosLO8zH8TN0cJi8353EXqH6f6mHoJTsLI0WpcZ0Bql4g1QqlEb6cs34rJB53ydboClv8E1fIG1E15k83kTa5J7hoGUVHfzWP0sode1vZbdr7gpMtAzL+kpuHTOZ+YsS63HxC+M7lw4UPKBDZ1v0nPPX1rW177kGOMBzCHlqXhgK3fhMpZ9BZ58gFklFa4tqrbJSLq2jNYm4EWK7JM5TycMhkl4EwqEe4UdxXgj28WeehsBUChGqAS6ofpvHCf/mVg3cF7Px/MVhChA4JVPl8UV0sY5jlQwGXuEaNh10+yq0faSH9kWwkdCX3aeq2CXi5h5eB+Lac4Wt0YlnEmqZAVv1N01TqD29naXEuzJ2P5xw9rc1nWV1wiRmu1TQ+kwmoEbjGscIMxFO1tUfa1lPm30Ik1yKmitA5oIZTYGyXW9lPegsMOHxpkuTAZzw6KhCKUrdrP2XdPFT7fjelZe5fB/U4aEb8Y+S5OPYyaQQq1wVkI=
      file_glob: true
      file: MiiCam.*
      skip_cleanup: true
      on:
        tags: true

  ##############################################################################
  ## Documentation                                                            ##
  ##############################################################################

  - name: Documentation
    sudo: false
    language: python
    python:
    - 3.7
    cache: .pip

    before_install:
    - openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv -in ${TRAVIS_BUILD_DIR}/docs/deploy-key.enc -out ${TRAVIS_BUILD_DIR}/docs/deploy-key -d
    - git config --global user.name "Travis Deploy Bot"
    - git config --global user.email "miicam@fliphess.com"
    - chmod 600 ${TRAVIS_BUILD_DIR}/docs/deploy-key
    - eval `ssh-agent -s`
    - ssh-add ${TRAVIS_BUILD_DIR}/docs/deploy-key
    - pip3 install -r ${TRAVIS_BUILD_DIR}/docs/requirements.txt

    script:
    - git clone git@github.com:miicam/miicam.github.io.git ${TRAVIS_BUILD_DIR}/docs/docs-repo
    - cd ${TRAVIS_BUILD_DIR}/docs && mkdocs build --verbose --clean --strict
    - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd ${TRAVIS_BUILD_DIR}/docs/docs-repo && git add . && git commit -am "Update documention by travis" && git push -u origin master; fi;

    after_script:
    - ssh-add -D
    - rm ${TRAVIS_BUILD_DIR}/docs/deploy-key

  ##############################################################################
  ## Build updater util and send to pypi                                      ##
  ##############################################################################

  - name: Updater Utility
    sudo: false
    language: python
    python:
    - 3.7
    cache: .pip
    env:
    - "PYTHONPATH=${TRAVIS_BUILD_DIR}/tools/updater"

    before_script:
    - pip3 install ${TRAVIS_BUILD_DIR}/tools/updater

    script:
    - pytest ${TRAVIS_BUILD_DIR}/tools/updater/miicam_updater/tests.py

    deploy:
      provider: pypi
      user: miicam
      password:
        secure: doroVqkGJ4YldJoRf4dSrWXuQjtuPggzV9sM7wa0DkHw4p42Cj+KdkN5MnDGvKgTOxVntEEu3hWEkHm4iRM2wb/rvvNwKc4PV/XU8iJELSJobJwVVAmmA2cxRAk5CVr9tx8stdpKzR+o/T79xzOMmg5u3wRjXrc15v7WLV4flvY9UpsQRe7QfAfS5ggp4JCeiz6TJcJUEX/16jrMcedm4pwwoMHxSaqzoXkmldkTmrY/m745+11l6LrA4TlloyPDEaL4XlFY8OZmfzlYO89wfF+sGbwVwq5yAwPtw25x5lIGTCd+xn8G9+Aze/SJJX+374RHN2Q+U5LYi3eoTcOUcksY2RqrbgNCUXJRSR0yCsjA3Q1kqUDfe2ZZLwTSiela2Pn7bxNjvZzs2GBmRBebNiiM42D9R6QYRv4C5MWQBLd26UbnvoRSWAd0/hmXlYIJR+g9I5evgaY1yJkB4j8Mc5t1RUc5zRg/tmsxUq5OjqCdcBSze0SJv0Hj7o2iLYIjD9aefXl5HgBmTPPt9VlUS+t0BgNbJoCnlDDdzVq8H6AgLh6r1V0kkdoHlrXAj9CN/SN28Uzh8+jAVuCRyRn78mRrnFfvfJI1kPcUDPtaSD7OMRQW/C2guFlcScbQKNl7VqN/boSHuJyvMg5bPt7AUicQKCzYB6O1oAFwg4WzDp0=
      on:
        tags: true
        branch: master

