sudo: required
dist: bionic
language: python
python: 3.6
git:
  submodules: false

env:
  global:
  - 'CACHEDIR=/home/travis/.cache/miicam/src'
  - 'WEBHOOK=https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh'
  jobs:
  - ELEMENT=Build
  - ELEMENT=Documentation

cache:
  directories:
    - /home/travis/.cache/miicam/src

services:
- docker

jobs:
  include:
  - name: Build
    env: ELEMENT=Build
    before_install:
    - docker ps -a
    - docker pull quay.io/miicam/miicam
    - docker build --cache-from quay.io/miicam/miicam -t miicam/miicam .
    script:
    - mkdir -p "${CACHEDIR}"
    - docker run -i -v "$(pwd):/result" -v "${CACHEDIR}:/env/src" --detach=false --rm --tty=true miicam/miicam /bin/bash -c 'make images clean && cp /env/MiiCam.* /result/'
    after_success:
    - test $TRAVIS_EVENT_TYPE = "cron" && bash .ci/nightly-build.sh

  - name: Documentation
    env: ELEMENT=Documentation
    before_install:
    - openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv -in docs/deploy-key.enc -out docs/deploy-key -d
    - git config --global user.name "Travis Deploy Bot"
    - git config --global user.email "miicam@fliphess.com"
    - chmod 600 docs/deploy-key
    - eval `ssh-agent -s`
    - ssh-add docs/deploy-key
    install:
    - pip install -r docs/requirements.txt
    - git clone git@github.com:miicam/miicam.github.io.git docs/docs-repo
    script:
    - cd docs && mkdocs build --verbose --clean --strict
    after_success:
    - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then cd docs/docs-repo && git add . && git commit -am "Update documention by travis" && git push -u origin master; fi;
    after_script:
    - ssh-add -D
    - rm docs/deploy-key

after_success:
- wget -O /tmp/send.sh "${WEBHOOK}" && chmod +x /tmp/send.sh && /tmp/send.sh success $DISCORD_WEBHOOK_URL

after_failure:
- wget -O /tmp/send.sh "${WEBHOOK}" && chmod +x /tmp/send.sh && /tmp/send.sh failure $DISCORD_WEBHOOK_URL

notifications:
  email: false
  webhooks:
    urls:
    - "$WEBHOOK_URL"
    on_success: change
    on_failure: always
    on_start: never

deploy:
  provider: releases
  api_key:
    secure: tQzN8M2tmdruwXiISw3rXMoz9ZNNOIabOC9MCxjihbQiQ5rXC3dqRlqtq3YC5PIg+FkfPuTH7OLH9QrC1N2O6sPD8VKsDkFMHyY3NG6AXfvpBVAP+u0RfH2hOxVQyMQ5DnvSFlGcYkef3X7OypRHcFSJSx5+IZHkPFkOpSxVQJu3PCGicO4qFRa2ALev/hosLO8zH8TN0cJi8353EXqH6f6mHoJTsLI0WpcZ0Bql4g1QqlEb6cs34rJB53ydboClv8E1fIG1E15k83kTa5J7hoGUVHfzWP0sode1vZbdr7gpMtAzL+kpuHTOZ+YsS63HxC+M7lw4UPKBDZ1v0nPPX1rW177kGOMBzCHlqXhgK3fhMpZ9BZ58gFklFa4tqrbJSLq2jNYm4EWK7JM5TycMhkl4EwqEe4UdxXgj28WeehsBUChGqAS6ofpvHCf/mVg3cF7Px/MVhChA4JVPl8UV0sY5jlQwGXuEaNh10+yq0faSH9kWwkdCX3aeq2CXi5h5eB+Lac4Wt0YlnEmqZAVv1N01TqD29naXEuzJ2P5xw9rc1nWV1wiRmu1TQ+kwmoEbjGscIMxFO1tUfa1lPm30Ik1yKmitA5oIZTYGyXW9lPegsMOHxpkuTAZzw6KhCKUrdrP2XdPFT7fjelZe5fB/U4aEb8Y+S5OPYyaQQq1wVkI=
  file_glob: true
  file: MiiCam.*
  skip_cleanup: true
  on:
    tags: true
